i put a company logo, and a gif
manoeltech/barbearia-devs pull request #2
Opened 2023-07-01 18:12 UTC by stinkk123

coloquei um gif animado e fiz uma logo para o site

2023-07-01 20:02 UTC, manoeltech requested changes
Mateus, coloquei sugestões para você alterar

2023-07-01 20:02 UTC, manoeltech commented on assets/img/referencia_inic.jpg
Mateus, no projeto não precisa ter essa imagem. Pode apagar ela, commitar e dar um push de novo

2023-07-01 20:02 UTC, manoeltech commented on index.html
> +<html lang="en">
aqui não precisa mexer, pode voltar para o 'pt-br' mesmo

2023-07-01 20:02 UTC, manoeltech commented on readme
Pode deixar que o readme eu faço, pois usamos o readme para dar um resumo ao projeto. Mas para corriir, a extensão seria 'readme.md'

2023-07-01 20:04 UTC, stinkk123 commented on assets/img/referencia_inic.jpg
Muito obrigado, vou alterar

2023-07-03 21:49 UTC, manoeltech approved these changes

2023-07-03 21:49 UTC, manoeltech commented on index.html
> +    <title>BarberShopDevs</title>
Permanecer o antigo titulo

2023-07-03 21:49 UTC, merged